<x-dashboard-layout>
    <x-slot:title>Create Category - Dashboard</x-slot:title>

    <div class="max-w-2xl mx-auto py-8">
        <!-- Header -->
        <div class="mb-8">
            <a href="{{ route('categories.index') }}" class="inline-flex items-center text-blue-600 hover:text-blue-800 mb-4">
                <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path>
                </svg>
                Back to Categories
            </a>
            <h1 class="text-3xl font-bold text-gray-900">Create New Category</h1>
        </div>

        <!-- Form Card -->
        <div class="bg-white rounded-lg shadow-md p-6 border border-gray-200">
            <form action="{{ route('categories.store') }}" method="POST" class="space-y-6">
                @csrf

                <!-- Name Field -->
                <div>
                    <label for="name" class="block text-sm font-bold text-gray-900">Category Name <span class="text-red-600">*</span></label>
                    <input type="text" id="name" name="name" required autofocus
                        class="mt-2 block w-full px-4 py-2 border border-gray-300 rounded-lg shadow-sm focus:ring-blue-500 focus:border-blue-500 @error('name') border-red-500 @enderror"
                        placeholder="Enter category name" value="{{ old('name') }}">
                    @error('name') 
                        <p class="text-red-600 text-sm mt-1">{{ $message }}</p> 
                    @enderror
                    <p class="text-gray-500 text-xs mt-1">The category name will be displayed publicly.</p>
                </div>

                <!-- Slug Field (Optional) -->
                <div>
                    <label for="slug" class="block text-sm font-bold text-gray-900">Slug <span class="text-gray-500 text-xs">(Optional)</span></label>
                    <input type="text" id="slug" name="slug"
                        class="mt-2 block w-full px-4 py-2 border border-gray-300 rounded-lg shadow-sm focus:ring-blue-500 focus:border-blue-500 @error('slug') border-red-500 @enderror"
                        placeholder="category-slug (leave empty to auto-generate)" value="{{ old('slug') }}">
                    @error('slug') 
                        <p class="text-red-600 text-sm mt-1">{{ $message }}</p> 
                    @enderror
                    <p class="text-gray-500 text-xs mt-1">Leave empty to auto-generate from category name.</p>
                </div>

                <!-- Submit Buttons -->
                <div class="flex gap-4 pt-4 border-t">
                    <button type="submit" class="px-6 py-2 bg-blue-600 text-white font-medium rounded-lg hover:bg-blue-700 transition">
                        Create Category
                    </button>
                    <a href="{{ route('categories.index') }}" class="px-6 py-2 bg-gray-300 text-gray-800 font-medium rounded-lg hover:bg-gray-400 transition">
                        Cancel
                    </a>
                </div>
            </form>
        </div>
    </div>

    <script>
        // Auto-generate slug from name
        const nameInput = document.getElementById('name');
        const slugInput = document.getElementById('slug');
        
        nameInput.addEventListener('input', function() {
            if (!slugInput.value || slugInput.dataset.autoGenerated) {
                const slug = this.value
                    .toLowerCase()
                    .replace(/[^a-z0-9]+/g, '-')
                    .replace(/^-+|-+$/g, '');
                slugInput.value = slug;
                slugInput.dataset.autoGenerated = 'true';
            }
        });
        
        slugInput.addEventListener('input', function() {
            if (this.value) {
                delete this.dataset.autoGenerated;
            }
        });
    </script>
</x-dashboard-layout>